### ISSUE TITLE
Tab indentation?

### ISSUE THREAD

**Issue by cboulanger** [Dominic-DallOsto/zotero-api-endpoint#1]
@Dominic-DallOsto The linter demands tab indentation, is this something that is important to you? I would rather use spaces (for example, the view on GitHub is messed up by tabs: https://github.com/Dominic-DallOsto/zotero-api-endpoint/blob/master/content/endpoint-manager.ts) and convert the tabs to spaces in my first PR. But of course, you created the project so I would respect it.

**Comment by Dominic-DallOsto** [comment]
I prefer tabs so I can view the code at different indentations. Does it work for you to set the size you want in your editor?

I can remove the linting rule if it's not working for you? Or change it to no-mixed-tabs-and-spaces if that's easier?

That section in the code should definitely use spaces though, I messed that up!

**Comment by cboulanger** [comment]
Not a big deal, I can live with tabs. I'll fix the indentation.
